spring:
  # 环境设置：dev、test、prod
  #  spring.profiles.active=dev
  profiles:
    active: prod

  datasource:
    username: chen
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/blog_cms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 8001